name: CI

on:
  push:
    branches: main
    tags: v*
  pull_request:
    branches: "*"

jobs:
  push:
    name: push
    runs-on: ubuntu-latest

    permissions:
      # https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
      id-token: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run lint:ci
      - run: yarn run test

      - run: yarn pack
      - name: Publish to NPM (dry run)
        # `yarn publish` does not support --provenance
        run: npm publish foxglove-rosmsg-*.tgz --provenance --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Publish to NPM
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        # `yarn publish` does not support --provenance
        run: npm publish foxglove-rosmsg-*.tgz --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
